### ISSUE TITLE
identation

### ISSUE THREAD

**Issue by birbified** [Nuggies-bot/nuggies-npm#12]
why the indentation in readme bad
readme not that hard to make

**Comment by pro-gamer007** [comment]
why dont you fork and change the readme :man:

**Comment by Assassin-1234** [comment]
I just copied the examples from the test code lol, we use eslint so idk if indentation is bad

**Comment by pro-gamer007** [comment]
he's talking abt the readme :neutral_face:

**Comment by Assassin-1234** [comment]
> he's talking abt the readme 😐

yeah the code examples in readme is from the test file

**Comment by pro-gamer007** [comment]
ohhh 😳

**Comment by Assassin-1234** [comment]
ight will fix the indentation on the docs, thanks for reporting
