### ISSUE TITLE
readme.md too long

### ISSUE THREAD

**Issue by face-hh** [Nuggies-bot/nuggies-npm#15]
you guys need docs.. readme is so hard to read :|

**Comment by Assassin-1234** [comment]
![image](https://user-images.githubusercontent.com/68866924/124634873-ad7cb500-de3b-11eb-9225-5b2d03f5740a.png)
I was just talking to pro about that lol

**Comment by face-hh** [comment]
:+1:

**Comment by Assassin-1234** [comment]
our docs maker is out of town (he says)
