### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by birbified** [Nuggies-bot/nuggies-npm#16]
instead of making a repo for each feature just make a folder named examples

**Comment by face-hh** [comment]
i agree

**Comment by pro-gamer007** [comment]
I was gonna tell this to ass but then frgt 😳

**Comment by Assassin-1234** [comment]
we'll make a seperate repo for examples, kinda like a whole bot ig lol

**Comment by birbified** [comment]
by the time you've finished the npm there will be a lot, i think you're better off with a single folder or readme

**Comment by Assassin-1234** [comment]
ight new folder examples

**Comment by birbified** [comment]
gonna close this cause dead
