### ISSUE TITLE
Add Typescript for Intellisense

### ISSUE THREAD

**Issue by hasib-rashid** [Nuggies-bot/nuggies-npm#27]
**Is your feature request related to a problem? Please describe.**
It will be awesome if you guys can adapt something like Typescript for the clear and concise intellisense of the package. It is just optional cuz like 95% of the devs use javascript but it would be nice to have such a feature :)

I could be making future pr's regarding this.

Love the package. Keep Going 👍🏻

**Comment by Assassin-1234** [comment]
its already on our todo list https://github.com/Nuggies-bot/nuggies-npm/projects/1#card-63738952

**Comment by hasib-rashid** [comment]
Oh okay sorry for disturbing. Keep on the package :)
