### ISSUE TITLE
Type Error: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by skibop** [Nuggies-bot/nuggies-npm#39]
**Describe the bug**
Type Error:   
message.guild.members.cache.get(user).send(dmEmbed);
                                                                             ^

TypeError: Cannot read property 'send' of undefined
    at \nuggies\src\classes\giveaways.js:109:43

**To Reproduce**
Simply just run a giveaway

**Expected behavior**
Supposed to run smoothly

**Desktop**
 -Windows
 - Latest Version
 - Node Version - v16.4.0

**Additional context**
Was working fine a day ago, then I think after a new update in giveaways, a bug happened

**Comment by Assassin-1234** [comment]
hey there! sorry for the delay, I was sleeping

anyways, I cannot reproduce the bug, can you please tell me what version of nuggies npm you are using?
![image](https://user-images.githubusercontent.com/68866924/127729835-6e5e5b4b-d5ea-4db1-be1d-d192a84d9b11.png)
![image](https://user-images.githubusercontent.com/68866924/127729837-1d6e3278-5414-4baa-9a3a-d6d36f2d2a1f.png)

the winner returns undefined i.e either there are no winners or one of the winners left the server. I'd make sure to fix this in the next update but I need more information on how to reproduce this bug, were there any participants in the giveaway?

**Comment by skibop** [comment]
I am using the latest version of nuggies, I uninstalled, and reinstalled. It seems that when I restart the bot when there are giveaways running, the error comes up.

**Comment by Assassin-1234** [comment]
I see where the problem is from, a document seems bugged in your database, It chooses a winner from the array but however the user doesnt exists in the guild so it returns the error. You can either search for `{ ended: false }` in your giveaways collection and delete the document (or all) or wait for the next update of the package. Also please join the support server so I can give you the bug hunter role https://discord.gg/X8v22CPwFN

**Comment by Assassin-1234** [comment]
let me know if you need anything else

**Comment by skibop** [comment]
Oh ok, I will let you know if I experience any other problems.

**Comment by Assassin-1234** [comment]
can I close this?

**Comment by skibop** [comment]
You may close this
