### ISSUE TITLE
Interaction Failed, Button Roles

### ISSUE THREAD

**Issue by skibop** [Nuggies-bot/nuggies-npm#40]
**Describe the bug**
When making button roles, everything works clearly, but on click of the button, a sign appears of "This Interaction Failed"

**To Reproduce**
Make a button role
Click On The Button
You should see the "This Interaction Failed" message

**Expected behavior**
Give the role to the user when clicked

**Screenshots**
![Button](https://user-images.githubusercontent.com/81841025/127749277-d791ede3-4ccc-4697-acd7-81deb53e04ba.png)

**Desktop (please complete the following information):**
 - Windows
 - Latest Version of Nuggies
 - Node version is v16.4.0

**Additional context**
I have everything copied and pasted from github, nothing appears in MongoDB, no errors in the console. I also have discord-buttons required, so im not sure what the problem is.

**Comment by Assassin-1234** [comment]
make sure you have ```js
Nuggies.handleInteractions(client)
```

in your code. Sorry for late response, I was sleeping
