### ISSUE TITLE
People won't be able to enter giveaways when the bot would be down.

### ISSUE THREAD

**Issue by Monochromish** [Nuggies-bot/nuggies-npm#49]
# Description
Discord still needs to improve buttons as if the bot would be down, people won't be able to enter giveaway, it would just reply with 'this interaction failed'. It would be better if you could also add reactions support in the package.

**Comment by Assassin-1234** [comment]
alright

**Comment by Assassin-1234** [comment]
we will be adding an option to choose either reaction or buttons in the next few updates and perform the task accordingly, thanks for the suggestion. Will keep you updated on it

**Comment by Monochromish** [comment]
Okay Thank you
