### ISSUE TITLE
Giveaways

### ISSUE THREAD

**Issue by CZISIS** [Nuggies-bot/nuggies-npm#5]
Hey,
make it possible to make a giveaway without a mongodb in else fs or quick.db

**Comment by Assassin-1234** [comment]
alright, will implement this

**Comment by sujalgoel** [comment]
well, MongoDB is suggested if you are using a host that works on ephemeral storage, which can reset your database on restart!. So, I don't think it is necessary to make it for quick DB.

**Comment by Assassin-1234** [comment]
We believe in flexibility so everyone can use the package without restrains

**Comment by Assassin-1234** [comment]
Wont be added. We'll have to change literally everything if we add this and could potentially bring some big bugs.
