### ISSUE TITLE
Mongodb connect

### ISSUE THREAD

**Issue by Lcxd65** [Nuggies-bot/nuggies-npm#50]
Hello, why if i use your package i cant put my mongodb link into an env file?
I did Nuggies.connect(process.env.MONGO)

**Comment by skibop** [comment]
You can do that, at the top you would have to include require("dotenv").config()

**Comment by Assassin-1234** [comment]
You can connect using .env. Make sure you use the dotenv module and use the same var you named in the env file. This is not related to the package.

**Comment by Toskan4134** [comment]
This is still not working

**Comment by Toskan4134** [comment]
This is my error and I don't know how to solve it. I also did it only using the string, without the process.env
![image](https://user-images.githubusercontent.com/62228706/182041494-4003b44e-c1b2-4b51-aecc-41a21210601e.png)
![image](https://user-images.githubusercontent.com/62228706/182041497-126ce686-fc6b-4b24-bfb5-02bbbfe303fc.png)

**Comment by Assassin-1234** [comment]
you are trying to access process.env without configuring dotenv, put the 
```js
require('dotenv').config()
```
line on top of everything, also just a side note, make sure the env file is in root directory

**Comment by Assassin-1234** [comment]
furthermore please make sure not to ask for help here since its strictly for package related bugs. This is a coding matter and not related to package
