### ISSUE TITLE
Cannot read property of "giveawayMessages" of undefiend.

### ISSUE THREAD

**Issue by face-hh** [Nuggies-bot/nuggies-npm#61]
All info is mentionated [here](https://github.com/Nuggies-bot/nuggies-npm/pull/59)

**Comment by LegItMate** [comment]
Do you have the function [Messages](https://nuggies.js.org/docs/classes/giveaways.html#methods) in your index.js or ready event?

**Comment by face-hh** [comment]
thinking emoji

**Comment by face-hh** [comment]
Hows it supposed to look, and whats it for if it requires only the client param?

**Comment by LegItMate** [comment]
Here's an example:
```js
Nuggies.giveaways.Messages(client, {}); // The options can be empty for default ones
```

**Comment by face-hh** [comment]
:roll_eyes: docs says opposite

**Comment by LegItMate** [comment]
Docs aren't completed so there may be some wrong options, etc.

**Comment by face-hh** [comment]
if (!message.client.customMessages.giveawayMessages) message.client.customMessages.giveawayMessages = defaultManagerOptions;
                                           ^

TypeError: Cannot read property 'giveawayMessages' of undefined


          Nuggies.giveaways.Messages(client, {});
          Nuggies.giveaways.create({

:smile:

**Comment by face-hh** [comment]
nice it crashed the bot

**Comment by LegItMate** [comment]
What djs version?

**Comment by face-hh** [comment]
changed it to

    Nuggies.giveaways.Messages(client, {
      dmWinner: true,
      giveaway: '🎉 **GIVEAWAY** 🎉',
      giveawayDescription: '🎁 Prize: **{prize}**\n🎊 Hosted by: {hostedBy}\n⏲️ Winner(s): `{winners}`\n\nRequirements: {requirements}',
      endedGiveawayDescription: '🎁 Prize: **{prize}**\n🎊 Hosted by: {hostedBy}\n⏲️ Winner(s): {winners}',
      giveawayFooterImage: 'https://cdn.discordapp.com/emojis/843076397345144863.png',
      winMessage: '{winners} you won {prize} Congratulations! Hosted by {hostedBy}',
      rerolledMessage: 'Rerolled! {winner} is the new winner of the giveaway!', // only {winner} placeholder
      toParticipate: '**Click the Enter button to enter the giveaway!**',
      newParticipant: 'You have successfully entered for this giveaway', // no placeholders | ephemeral
      alreadyParticipated: 'you already entered this giveaway!', // no placeholders | ephemeral
      noParticipants: 'There are not enough people in the giveaway!', // no placeholders
      noRole: 'You do not have the required role(s)\n{requiredRoles}\n for the giveaway!', // only {requiredRoles} | ephemeral
      dmMessage: 'You have won a giveaway in **{guildName}**!\nPrize: [{prize}]({giveawayURL})',
      noWinner: 'Not enough people participated in this giveaway.', // no {winner} placerholder
      alreadyEnded: 'The giveaway has already ended!', // no {winner} placeholder
      dropWin: '{winner} Won The Drop!!', // only {winner} placeholder
    });

and its still

**Comment by face-hh** [comment]
Fixed by deleting the old data, is it possible to add multiple roles in the requirements?

**Comment by face-hh** [comment]
why bruh, clicker is removed in v13
![image](https://user-images.githubusercontent.com/69168154/131344765-e19c4739-9778-466c-97f1-742b8b98ffee.png)

**Comment by LegItMate** [comment]
> Fixed by deleting the old data, is it possible to add multiple roles in the requirements?

Yes that's why its an array

**Comment by face-hh** [comment]
sussy baka
![image](https://user-images.githubusercontent.com/69168154/131344935-bddd1f74-75f6-4cc0-8b16-1ce5b294dc27.png)

**Comment by LegItMate** [comment]
> why bruh, clicker is removed in v13
> ![image](https://user-images.githubusercontent.com/69168154/131344765-e19c4739-9778-466c-97f1-742b8b98ffee.png)

Missed one 💀

**Comment by face-hh** [comment]
bruh, and no one noticed

**Comment by LegItMate** [comment]
As I said, missed one 🤷

**Comment by Assassin-1234** [comment]
what version are you using? cuz I remember reverting the changes in v1.3.8, still I havent seen the repo activity in a while so I might be wrong

**Comment by pro-gamer007** [comment]
he said in dsc

**Comment by face-hh** [comment]
:weary:

**Comment by Assassin-1234** [comment]
I think this is fixed so imma just close this xd
