### ISSUE TITLE
Button Roles Feature Request

### ISSUE THREAD

**Issue by ChillNotTaken** [Nuggies-bot/nuggies-npm#7]
Can u add br edit, br lost br remove,etc?

In the button roles code ex repo

**Comment by Assassin-1234** [comment]
sure thing

**Comment by Assassin-1234** [comment]
added to the todo list, you can track it here https://github.com/Nuggies-bot/nuggies-npm/projects/1

**Comment by Assassin-1234** [comment]
coming out in the next version

**Comment by Assassin-1234** [comment]
this has finally been added in the new update that is due this week, would close this
